# Generated by Django 4.1.3 on 2022-11-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Father_Name', models.CharField(default='', max_length=50)),
                ('Gender', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=50)),
                ('File', models.ImageField(upload_to='myimage')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('Father_name', models.CharField(default='', max_length=50)),
                ('Gender', models.CharField(default='', max_length=50)),
                ('Class', models.CharField(default='', max_length=50)),
                ('Section', models.CharField(default='', max_length=50)),
                ('Roll_No', models.CharField(default='', max_length=50)),
                ('Photo', models.ImageField(upload_to='myimage')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
