# Generated by Django 4.1.3 on 2022-11-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("latestTech", "0002_rename_email_information_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="information", old_name="father_Name", new_name="father_name",
        ),
    ]
